<?php

namespace AppBundle\Repository;

/**
 * AvatarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarsRepository extends \Doctrine\ORM\EntityRepository
{
}
