<?php

namespace AppBundle\Repository;

/**
 * ComptesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptesRepository extends \Doctrine\ORM\EntityRepository
{
}
