<?php

namespace AppBundle\Repository;

/**
 * EquipeMembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeMembresRepository extends \Doctrine\ORM\EntityRepository
{
}
