<?php

namespace AppBundle\Repository;

/**
 * InfosMangoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosMangoRepository extends \Doctrine\ORM\EntityRepository
{
}
