<?php

namespace AppBundle\Repository;

/**
 * StatutJoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutJoueurRepository extends \Doctrine\ORM\EntityRepository
{
}
