app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

apiuser:
    type:     rest
    resource: AppBundle\Controller\ApiUserController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

departements:
    type:     rest
    resource: AppBundle\Controller\DepartementsControllerController

statuts:
    type:     rest
    resource: AppBundle\Controller\StatutController

lieux:
    type:     rest
    resource: AppBundle\Controller\Departements\LieuxController

avatars:
    type:     rest
    resource: AppBundle\Controller\Membres\AvatarsController

membres:
    type:     rest
    resource: AppBundle\Controller\MembresController

comptes:
    type:     rest
    resource: AppBundle\Controller\Membres\ComptesController

infos_mango:
    type:     rest
    resource: AppBundle\Controller\Membres\InfosMangoController

evenements:
    type:     rest
    resource: AppBundle\Controller\Departements\Lieux\EvenementsController

equipes:
    type:     rest
    resource: AppBundle\Controller\Evenements\EquipesController